Core/Core/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core.Models;
using Core.DataAccess.Data.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Core.Utility;

namespace Core.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _iunitOfWork;

        public CategoryController(IUnitOfWork iunitOfWork)
        {
            _iunitOfWork = iunitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Category category = new Category();
            if (id == null)
            {
                return View(category);
            }

            category = _iunitOfWork.Category.Get(id.GetValueOrDefault());
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        public IActionResult Upsert(Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.Id == 0)   //this is create ...
                {
                    _iunitOfWork.Category.Add(category);
                }
                else                    //this is an update ...
                {
                    _iunitOfWork.Category.Update(category);
                }

                _iunitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }


        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            // return Json(new { data = _iunitOfWork.Category.GetAll() });
            return Json(new { data = _iunitOfWork.SP_Call.ReturnList<Category>(SD.usp_GetAllCategory, null) });
        }


        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objectFromDb = _iunitOfWork.Category.Get(id);
            if (objectFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting ..." });
            }

            _iunitOfWork.Category.Remove(objectFromDb);
            _iunitOfWork.Save();
            return Json(new { success = true, message = "Deleted Successfully" });
        }

        #endregion

    }
}

Core/Core/Areas/Admin/Controllers/OrderController.cs
using Core.DataAccess.Data.Repository.IRepository;
using Core.Models.ViewModels;
using Core.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Core.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            OrderViewModel orderVM = new OrderViewModel()
            {
                OrderHeader = _unitOfWork.OrderHeader.Get(id),
                OrderDetails = _unitOfWork.OrderDetails.GetAll(filter: o => o.OrderHeaderId == id)
            };

            return View(orderVM);
        }

        public IActionResult Approve(int id)
        {
            var orderFromDb = _unitOfWork.OrderHeader.Get(id);
            if (orderFromDb == null)
            {
                return NotFound();
            }
            _unitOfWork.OrderHeader.ChangeOrderStatus(id, SD.StatusApproved);
            return View(nameof(Index));
        }

        public IActionResult Reject(int id)
        {
            var orderFromDb = _unitOfWork.OrderHeader.Get(id);
            if (orderFromDb == null)
            {
                return NotFound();
            }
            _unitOfWork.OrderHeader.ChangeOrderStatus(id, SD.StatusRejected);
            return View(nameof(Index));
        }



        #region API Calls

        public IActionResult GetAllOrders()
        {
            return Json(new { data = _unitOfWork.OrderHeader.GetAll() });
        }

        public IActionResult GetAllPendingOrders()
        {
            return Json(new { data = _unitOfWork.OrderHeader.GetAll(filter: o => o.Status == SD.StatusSubmitted) });
        }

        public IActionResult GetAllApprovedOrders()
        {
            return Json(new { data = _unitOfWork.OrderHeader.GetAll(filter: o => o.Status == SD.StatusApproved) });
        }

        #endregion
    }
}

Core/Core/Areas/Admin/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using Core.DataAccess.Data.Repository.IRepository;
using Core.Models.ViewModels;
using Core.Models;
using Microsoft.AspNetCore.Authorization;

namespace Core.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class ServiceController : Controller
    {
        private readonly IUnitOfWork _iUnitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        
        [BindProperty]
        public ServiceVM ServVM { get; set; }

        public ServiceController(IUnitOfWork iUnitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _iUnitOfWork = iUnitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            ServVM = new ServiceVM()
            {
                Service = new Service(),
                CategoryList = _iUnitOfWork.Category.GetCategoryListForDropDown(),
                FrequencyList = _iUnitOfWork.Frequency.GetFrequencyListForDropDown(),
            };

            if (id != null)
            {
                ServVM.Service = _iUnitOfWork.Service.Get(id.GetValueOrDefault());
            }

            return View(ServVM);
        }

        [HttpPost]
        public IActionResult Upsert()
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                if (ServVM.Service.Id == 0)
                {
                    //Create New Service

                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(webRootPath, @"images\services");
                    var extention = Path.GetExtension(files[0].FileName);

                    using(var fileStrams= new FileStream(Path.Combine(uploads, fileName + extention), FileMode.Create))
                    {
                        files[0].CopyTo(fileStrams);
                    }

                    ServVM.Service.ImageUrl = @"\images\services\"+fileName+extention;
                    _iUnitOfWork.Service.Add(ServVM.Service);
                }
                else
                {
                    //Edit the Service

                    var ServiceFromDb = _iUnitOfWork.Service.Get(ServVM.Service.Id);
                    if (files.Count > 0)
                    {
                        string fileName = Guid.NewGuid().ToString();
                        var uploads = Path.Combine(webRootPath, @"images\services");
                        var extention_new = Path.GetExtension(files[0].FileName);

                        var imagePath = Path.Combine(webRootPath, ServiceFromDb.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }

                        using (var fileStrams = new FileStream(Path.Combine(uploads, fileName + extention_new), FileMode.Create))
                        {
                            files[0].CopyTo(fileStrams);
                        }

                        ServVM.Service.ImageUrl = @"\images\services\" + fileName + extention_new;
                    }
                    else
                    {
                        ServVM.Service.ImageUrl = ServiceFromDb.ImageUrl;
                    }

                    _iUnitOfWork.Service.Update(ServVM.Service);
                }

                _iUnitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            ServVM.CategoryList = _iUnitOfWork.Category.GetCategoryListForDropDown();
            ServVM.FrequencyList = _iUnitOfWork.Frequency.GetFrequencyListForDropDown();
            return View(ServVM);
        }


        #region API Calls

        public IActionResult GetAll()
        {
            return Json(new { data = _iUnitOfWork.Service.GetAll(inculdeProperties: "Category,Frequency") });
        }

        public IActionResult Delete(int id)
        {
            var ServiceFromDb = _iUnitOfWork.Service.Get(id);
            string webRootPath = _hostEnvironment.WebRootPath;

            var imagePath = Path.Combine(webRootPath, ServiceFromDb.ImageUrl.TrimStart('\\'));

            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }

            if (ServiceFromDb == null)
            {
                return Json(new { sucsses = false, message = "Error while deleting ..." });
            }

            _iUnitOfWork.Service.Remove(ServiceFromDb);
            _iUnitOfWork.Save();

            return Json(new { success = true, message = "Deleted successfully" });
        }

        #endregion
    }
}

Core/Core/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Core.DataAccess.Data.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Core.Utility;

namespace Core.Areas.Admin.Controllers
{
    [Authorize(Roles =SD.Admin)]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _iUnitOfWork;

        public UserController(IUnitOfWork iUnitOfWork)
        {
            _iUnitOfWork = iUnitOfWork;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            return View(_iUnitOfWork.User.GetAll(u=>u.Id!=claims.Value));
        }

        public IActionResult Lock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            _iUnitOfWork.User.LockUser(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            _iUnitOfWork.User.UnLockUser(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Core/Core/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-success form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-primary form-control">Back To List</a>
    </div>
</div>

Core/Core/Views/Shared/_EditAndBackToListButton.cshtml
@model int

    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-success form-control" asp-route-id="@Model">Update</button>
        </div>
        <div class="col">
            <a asp-action="Index" class="btn btn-primary form-control">Back To List</a>
        </div>
    </div>

Core/Core/Views/Shared/_Layout.cshtml
@using Core.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor
@using Core.Extentions

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">Core</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarColor01" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole(SD.Admin) || User.IsInRole(SD.Manager))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropDown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDown">
                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Frequency" asp-action="Index">Frequency</a>
                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Service" asp-action="Index">Service</a>
                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Order" asp-action="Index">Order</a>
                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="WebImage" asp-action="Index">Image Uploader</a>

                                    @if (User.IsInRole(SD.Admin))
                                    {
                                        <a class="dropdown-item text-white" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                                    }
                                </div>
                            </li>
                        }

                        @if (httpContextAccessor.HttpContext.Session.GetObject<List<int>>(SD.SessionCart) != null)
                        {
                            <li style="color:white">
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link text-white">
                                    @{
                                        var count = httpContextAccessor.HttpContext.Session.GetObject<List<int>>(SD.SessionCart).Count;
                                    }
                                    <i class="fas fa-shopping-cart"></i>&nbsp; (@count)
                                </a>
                            </li>
                        }

                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3 my-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white  bg-primary">
        <div class="container">
            &copy; 2021 - Core
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
        <script src="https://kit.fontawesome.com/e19c476714.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </environment>
</body>
</html>